services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
